version: "2"

linters:
  default: none
  enable:
    - decorder
    - dupword
    - dupl
    - errname
    - gocritic
    - gosec
    - gocyclo
    - ineffassign
    - makezero
    - misspell
    - revive
    - unused
    - usestdlibvars
  settings:
    govet:
      enable:
        - nilness
        - unusedwrite
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - dupl
    paths:
      - docs$
      - dist$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - docs$
      - dist$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
