name: Run unit tests

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  unit-test:
    name: unit-test-${{ matrix.arch }}
    runs-on: base-dind-2204-${{ matrix.arch }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Run bunny unit tests
        run: make unittest
